apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dz2luinja-nodejs-gitops
  description: This is GitOps manifest for dz2luinja-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=dz2luinja-nodejs
    backstage.io/kubernetes-id: dz2luinja-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dz2luinja-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dz2luinja-nodejs
